sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: v2fHuNO+bWjMJ1uOZJgtefAal9W7ylRyNcFVjvS1VskrN/yTF0Mlj/+cAupob90IhEqycHQ0HIIWHbRUrjT0NCRRDdSraNRP6uOohzPRIv1SmXpEyh/XuLjNH0lttLnpIQHPQnpIn9FU+1BdhXcADgrmKKhh0OgNDuJsJDLQehzqm8m6/GVTjuh5hR+gmVN0SzxIXqhTq1u4f3TI/UDTpmIP98kcxigOfWLURujumxIMP+E1QnnozakAkaGnNGz203x3T/xVFnvMTZuk3tyBoTsiQjwweOAwJ55AxQY+JgOFyncY4QCAc6iOc/bACzZpDWqrNQjN5aJqm54fqv7H5EQJ5rIXTVWDZWVq5bl7HW71rQvGJmWWNxj/9E4IxYSeWduBLDD6KJFAjjfalYQCtX7ZCMZ9fYTfRJikt8ShzwIkDG8a5h5ocM3D7v+cQ/iU97XQLY7rQsZDZlW1KJJLnAj/5hoKL4s9FkPj6GmOUQGO0vfS06tan0ClHLZiN2VtRQovdf79rRNE176CtN5qcVVEJFMKI4hLMLr12fvGKonjxu4ceh0x9sEU6CMwKHrJ4baGvbjGHlhK9FINnX835XzyAvmdE2bkmO54EeDrjf9sqylxbPe66pPg3uJXd4IdpXQsVHBHqOwbLfGnJzdKlbSlKNCOpNoMVyhd62AVJII=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Complete-Poetical-Works-of-Percy-Bysshe-Shelley-Volume-2_4798
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy